application: android-crash-reports
version: 1
runtime: python39
api_version: 1
app_engine_apis: true

handlers:
- url: /reports/.*
  script: auto
  login: admin
- url: /admin/.*
  script: auto
  login: admin
